version: '3'

services:

  nmap-wbe:
    build: .
    image: nmap-wbe:0.1
    container_name: nmap-wbe
    restart: always
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    environment:
      - LISTEN_ADDR=${LISTEN_ADDR}
      - LISTEN_PORT=${LISTEN_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
      - REDIS_URI=${REDIS_URI}
      - MIN_RESCAN_TIME=${MIN_RESCAN_TIME}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - NMAP_ARGUMENTS=${NMAP_ARGUMENTS}
    network_mode: "bridge"
